#THE SCRIPT BELOW OUTLINES CODE FOR ANALYZING BINNED (BY SESSION) UN DATA FOR EACH COUNTRY.
#USING THE BINNED DATA, WE WILL ASSESS THE RELATIONSHIPS BETWEEN THE WAY EACH COUNTRY VOTES
#AND DETERMINE WHICH COUNTRIES VOTE SIMILARLY. 

